### PR TITLE
Version 1.49.0

### PR DESCRIPTION
**Pull request by WilliamDEdwards**
# Changes

This PR updates the library to support Cluster API version 1.118.

# Checks

- [x] The version constant is updated in `Client.php`
- [x] The changelog is updated (when applicable)
- [x] The supported Cluster API version is updated in the README (when applicable)

### CODE REVIEW

**Comment by dvdheiden** [comment]
@WilliamDEdwards the API version is not yet released to production right? When do you expect that release?

**Comment by WilliamDEdwards** [comment]
> @WilliamDEdwards the API version is not yet released to production right? When do you expect that release?

The API has been released. This PR may be merged.

**Comment by WilliamDEdwards** [comment]
> @WilliamDEdwards the API version is not yet released to production right? When do you expect that release?

The API has been released. This PR may be merged.

**Comment by dvdheiden** [comment]
I will look at it tomorrow.

**Review by dvdheiden — APPROVED** [review]

**Pull request merged**
